### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by mbunal** [AyoobAli/easySQLite3#2]
hi 
i wonder that, can i use your easySQLite3 within try catch finaly??? for example:
```include "easySQLite3.class.php";

$db = new easySQLite3("database.sqlite");

$db->setTable( "NewTable" );

$db->setColumns("id", "int", true, false, true); // Column name is 'id',        type is 'INTEGER', will be primary column, and will be is_autoincremented.
$db->setColumns("mail", "text", false, true);    // Column name is 'mail',      type is 'TEXT',    will be unique column.
$db->setColumns("url", "char");                  // Column name is 'url',       type is 'TEXT'.
$db->setColumns("datestamp", "date");            // Column name is 'datestamp', type is 'NUMERIC'.
$db->setColumns("stt", "bool");                  // Column name is 'stt',       type is 'NUMERIC'.

    try {
        $db->createTable();
    } catch (Exception $e) {
        echo "Can't create the Table.";
    } finally {
        $db->clearColumns();
    }
    echo "Table was created successfully.";
```

**Comment by AyoobAli** [comment]
Hi @mbunal, sorry for the very late reply.

Regarding the try catch, This will not work as you expect, as it will not through an exception when it can't create the table.
The reason is that the function performs some checks before trying to create the table, for example it checks if the database is connected or not, table name provided, etc...

Then if it can't create the table, the function `$db->createTable();` will return `false` without throwing an exception.

But at the end of the function it executes the query using the SQLite3 function `exec($SQL_Query)` and it returns the response of `exec` function, so the only use of `try` here will be if the function `exec` throw an exception.


So, if you want to use try to make sure no errors in your code, you can do something like:

```php
try {
    $tableCreated = $db->createTable();
} catch (Exception $e) {
    $tableCreated = false;
}

if ( $tableCreated == false ) {
    echo "Can't create the Table.";
}else{
    echo "Table was created successfully.";
}

$db->clearColumns();
```
